name: conditional workflow
on:
  push:
    branches:
      - dev

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v4

      - name: Download Dependencies
        run: npm ci

      - name: Test
        id: test
        run: npm run test
        # 특정 step이 실패하더라도 진행
        # continue-on-error: true

      - name: Upload Test Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: coverage

      - name: Build Project
        id: build
        run: npm run build

      - name: Notify
        if: failure()
        run: echo "Test Failed"

      - name: Build Fail Notification
        if: failure() && steps.build.outcome == 'failure'
        run: echo "build Failed"
