name: build,test,deploy
on:
  pull_request:
    types:
      - opened

    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v4

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Download Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v4

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Download Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy..."
