name: build,test,deploy
on:
  pull_request:
    types:
      - opened
    branches:
      - main
  push:
    branches:
      - dev
      - dev-* # dev-new, dev-something
      - feat/** # feat/new, feat/something/new

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Paths
        run: pwd

      - name: Initialize Project
        uses: ./.github/actions

      - name: Build Project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          include-hidden-files: true
          path: .next

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v4

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Download Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build

      - name: Outputs
        run: ls -la

      - name: Deploy
        run: echo "Deploy..."
